### ISSUE TITLE
makefile to build them all

### ISSUE THREAD

**Issue by laoshaw** [c-blake/bu#1]
how to build them easily? Thanks.

**Comment by c-blake** [comment]
`nimble install bu` should work.  Will wind up in your `$HOME/.nimble/bin` (Well, I point my nimble to make that `/opt/nimble/bin` because I share binaries on a multi-user system).

**Comment by c-blake** [comment]
Oh, but I should have mentioned anything post the last released version might be missing that way...Let me know if you need a version bump for `tim` which is the only such tool.

**Comment by c-blake** [comment]
Oh, wait - maybe you are not on Linux?  I have not tested on Mac OSX in forever...

**Comment by c-blake** [comment]
It looks like "many" (perhaps > 65%?) of the tools will build if you do them 1-by-1.  Sorry.  I will look into this for a more smooth global install process, but maybe not until 4..5 hours from now.

**Comment by c-blake** [comment]
(But it would be helpful if you can paste/send the output of `nim -v`.)
