### ISSUE TITLE
Failed to build du on first try

### ISSUE THREAD

**Issue by laoshaw** [c-blake/bu#2]
nimble install cligen
nim c -r --verbosity:0 du.nim

```
/home/pie/.nimble/pkgs/cligen-1.5.33/cligen/statx.nim(271, 11) Error: type mismatch: got <string, Statx>
but expected one of:
proc statx(dirfd: cint; path: cstring; flags: cint; stx: var Statx;
           mask = statxMask): cint
  first type mismatch at position: 1
  required type for dirfd: cint
  but expression 'path' is of type: string

expression: statx(path, st)
```

**Comment by c-blake** [comment]
Hmm.  I have never seen this one before. :-)  Let me see if I can reproduce..

**Comment by c-blake** [comment]
What does `nim -v` output on your system?

**Comment by c-blake** [comment]
As per https://github.com/c-blake/bu/issues/1#issuecomment-1370017744 I see you are on Ubuntu.  I have some important errands to deal with over the next hour or so and will have to get back to this later.

**Comment by c-blake** [comment]
A quick update -- I have reproduced this on an Ubuntu 22 virtual machine.  I will look into a fix tomorrow.

**Comment by c-blake** [comment]
Ok.  There were a couple different problems that should be fixed now.   You may need to either a nimble refresh or blow away existing nimble data and then `nimble install bu` should hopefully work.

**Comment by c-blake** [comment]
(Also - I will leave this issue open until I hear back from you that you can install it.  So, please get back to me on that when it's convenient.)

**Comment by c-blake** [comment]
It actually should also work on Mac OSX and FreeBSD now..You inspired me to do a lot of Nim version and platform portability work.  (Some tools are pretty Linux-specific, though..I should mention that in their `doc/` files.)
