### ISSUE TITLE
githubcom_cblakebu_#head/bu/zipf.nim(10, 11) Error: cannot open file: std/syncio

### ISSUE THREAD

**Issue by Clonkk** [c-blake/bu#3]
Hi,

I tried to build from latet stable compiler 1.6.12 and I got the following error during the compilation of zipf : 

```
githubcom_cblakebu_#head/bu/zipf.nim(10, 11) Error: cannot open file: std/syncio
```

**Comment by Clonkk** [comment]
Well that was fast

**Comment by c-blake** [comment]
I think the build might still fail for you at `oft`.

**Comment by c-blake** [comment]
I think there is a very good chance it will work for you now (and produce like 67 binaries in your nimble bin directory).
